#!/bin/bash

currentDate=`date +"%m-%d-%Y-%H:%M:%S"`
mkdir ../../Output/$currentDate
./testerCacheScratch $currentDate $1
./testerCacheThrash $currentDate $1
./testerLinuxScalability $currentDate $1
./testerThreadTest $currentDate $1
